name: Continuous integration (CI) testing

on: [push, pull_request]

jobs:
  # Separate linting as a parallel test from unit/integration testing because
  # it does not need to be run in multiple environments.
  lint:
    name: Lint and unit testing
    runs-on: ubuntu-latest
    env:
      HUSKY: "0"
      CYPRESS_INSTALL_BINARY: "0"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # Use the current LTS version of Node.js
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm ci
    - run: npm run lint
    - run: npm run vitest

