name: Build and deploy

on: 
  push:
    branches:
      - paris_en_selle

jobs:
  build:
    name: Build
    env:
      HUSKY: "0"
      CYPRESS_INSTALL_BINARY: "0"
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm ci
    - run: npm run build
    - name: deploy
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --exclude .env
        path: .
        remote_path: /home/streetmix_user/streetmix
        remote_host: 54.38.35.47
        remote_user: streetmix_user
        remote_key: ${{ secrets.DEPLOY_KEY }}
